--
-- SCRIPT: Borrar y crear tablas
--

-- *************************
-- 1) Truncar tablas (si existen) en el orden correcto
-- *************************
BEGIN
    -- Ignorar error "table or view does not exist" (ORA-00942) en caso de que la tabla no exista
EXECUTE IMMEDIATE 'TRUNCATE TABLE Gestion_Reseña';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
        RAISE;
END IF;
END;
/

BEGIN
EXECUTE IMMEDIATE 'TRUNCATE TABLE Realiza';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
        RAISE;
END IF;
END;
/

BEGIN
EXECUTE IMMEDIATE 'TRUNCATE TABLE GestionPago';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
        RAISE;
END IF;
END;
/

BEGIN
EXECUTE IMMEDIATE 'TRUNCATE TABLE GestionCarrito';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
        RAISE;
END IF;
END;
/

BEGIN
EXECUTE IMMEDIATE 'TRUNCATE TABLE tiene';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
        RAISE;
END IF;
END;
/

BEGIN
EXECUTE IMMEDIATE 'TRUNCATE TABLE GestionPedido';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
        RAISE;
END IF;
END;
/

BEGIN
EXECUTE IMMEDIATE 'TRUNCATE TABLE modificaProducto';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
        RAISE;
END IF;
END;
/

-- Truncar tablas principales
BEGIN
EXECUTE IMMEDIATE 'TRUNCATE TABLE reseña';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
        RAISE;
END IF;
END;
/

BEGIN
EXECUTE IMMEDIATE 'TRUNCATE TABLE pedido';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
        RAISE;
END IF;
END;
/

BEGIN
EXECUTE IMMEDIATE 'TRUNCATE TABLE producto';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
        RAISE;
END IF;
END;
/

BEGIN
EXECUTE IMMEDIATE 'TRUNCATE TABLE pago';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
        RAISE;
END IF;
END;
/

BEGIN
EXECUTE IMMEDIATE 'TRUNCATE TABLE carrito';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
        RAISE;
END IF;
END;
/

BEGIN
EXECUTE IMMEDIATE 'TRUNCATE TABLE usuario';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
        RAISE;
END IF;
END;
/
COMMIT;
/

-- *************************
-- 2) Eliminar tablas (DROP) en el orden correcto
-- *************************
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE Gestion_Reseña PURGE';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
        RAISE;
END IF;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE Realiza PURGE';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
        RAISE;
END IF;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE GestionPago PURGE';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
        RAISE;
END IF;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE GestionCarrito PURGE';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
        RAISE;
END IF;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE GestionPedido PURGE';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
        RAISE;
END IF;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE modificaProducto PURGE';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
        RAISE;
END IF;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE tiene PURGE';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
        RAISE;
END IF;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE reseña PURGE';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
        RAISE;
END IF;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE pedido PURGE';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
        RAISE;
END IF;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE producto PURGE';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
        RAISE;
END IF;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE pago PURGE';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
        RAISE;
END IF;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE carrito PURGE';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
        RAISE;
END IF;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE usuario PURGE';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
        RAISE;
END IF;
END;
/
COMMIT;
/

-- Eliminar secuencia PAGO_SEQ si existe
BEGIN
EXECUTE IMMEDIATE 'DROP SEQUENCE PAGO_SEQ';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN -- ORA-02289: sequence does not exist
        RAISE;
END IF;
END;
/
COMMIT;
/

BEGIN
EXECUTE IMMEDIATE 'DROP SEQUENCE seq_id_pedido';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN -- ORA-02289: sequence does not exist
        RAISE;
END IF;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP SEQUENCE seq_id_carrito';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN
        RAISE;
END IF;
END;
/
COMMIT;
/